[package]
name = "chrultrabook_tools"
version = "2.8.4"
description = "chrultrabook-tools"
authors = ["Robinson Arysseril"]
license = "gpl-3.0"
repository = "https://github.com/death7654/Chrultrabook-Controller"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4", features = [] }

[dependencies]
tauri = { version = "1.4", features = [ "window-minimize", "window-unminimize", "system-tray", "icon-ico", "window-center", "window-close", "window-start-dragging", "window-hide", "window-show"] }
tauri-plugin-autostart = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.29.10"
hidapi = "2.4.1"
num_cpus = "1.16.0"
regex = "1.10.2"


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
