name: 'build linux appimage'
on: 
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with: 
         toolchain: 1.72
      - name: Install build dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          sudo apt-get install -y desktop-file-utils
      - name: Install npm dependencies
        run: npm install 
      - name: Build application
        run: npm run tauri build
      - name: Linux AppImage Packaging
        run: resources/linux_build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Chrultrabook-Controller
          retention-days: 5
          path: src-tauri/target/release/bundle/appimage/chrultrabook*.AppImage
