name: "macOS"
on:
  push:
    branches: ["3.X.X"]
  workflow_dispatch:
  pull_request:

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
      - name: Add Darwin Rust
        run: rustup target add x86_64-apple-darwin
      - name: Install Frontend Dependencies
        run: npm install # change this to npm or pnpm depending on which one you use
      - name: Build Application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install. Replace AppImage with one uploaded in artifact"
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
