name: "Linux"
on:
  push:
    branches: ["3.X.X"]
  workflow_dispatch:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install build dependencies
        run: |
          sudo apt update -y
          sudo apt install libwebkit2gtk-4.1-0=2.44.0-2 \
            libwebkit2gtk-4.1-dev=2.44.0-2 \
            libjavascriptcoregtk-4.1-0=2.44.0-2 \
            libjavascriptcoregtk-4.1-dev=2.44.0-2 \
            gir1.2-javascriptcoregtk-4.1=2.44.0-2 \
            gir1.2-webkit2-4.1=2.44.0-2 \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            desktop-file-utils \
            libudev-dev;
      - name: Install npm dependencies
        run: npm install
      - name: Build Application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: "v__VERSION__"
          releaseBody: "See the assets to download this version and install. Replace AppImage with one uploaded in artifact"
          releaseDraft: true
          prerelease: false
      - name: Linux AppImage Packaging
        run: ./linux_appimage.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Chrultrabook-tools
          retention-days: 5
          path: src-tauri/target/release/bundle/appimage/chrultrabook*.AppImage
