name: 'build linux'
on: [push]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-20.04, macOS-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with: 
         toolchain: 1.72
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf -y
          sudo apt-get install desktop-file-utils
      - name: install frontend dependencies
        run: npm install 
      - uses: tauri-apps/tauri-action@v0
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: 'App Name v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Linux AppImage Packaging
        if: matrix.platform == 'ubuntu-20.04'
        run: ./linux_build.sh
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Chrultrabook-Controller
          retention-days: 5
          path: src-tauri/target/release/bundle/appimage/*.AppImage
